/// Modular MVVM layer for UGO Admin. Legacy pages remain under `lib/pages`;
/// this package introduces repositories, contracts, and module hubs.
library admin_panel;

export 'admin_panel_dependencies.dart';
export 'core/admin_panel_session.dart';
export 'core/admin_staff_role.dart';
export 'core/loadable.dart';
export 'core/rbac_policy.dart';
export 'data/api/admin_api_contract.dart';
export 'data/api/admin_api_exception.dart';
export 'data/api/http_admin_api_client.dart';
export 'data/api/mock_admin_api_client.dart';
export 'data/models/analytics_models.dart';
export 'data/models/domain_enums.dart';
export 'data/models/driver_models.dart';
export 'data/models/finance_models.dart';
export 'data/models/notification_models.dart';
export 'data/models/promo_models.dart';
export 'data/models/rider_models.dart';
export 'data/models/ride_models.dart';
export 'data/models/settings_models.dart';
export 'data/models/vehicle_models.dart';
export 'data/repositories/analytics_admin_repository.dart';
export 'data/repositories/driver_admin_repository.dart';
export 'data/repositories/finance_admin_repository.dart';
export 'data/repositories/rides_admin_repository.dart';
export 'data/repositories/settings_admin_repository.dart';
export 'data/repositories/user_admin_repository.dart';
export 'modules/common/view_models/dashboard_analytics_view_model.dart';
export 'modules/common/view_models/finance_hub_view_model.dart';
export 'modules/common/view_models/operations_hub_view_model.dart';
export 'modules/driver/view_models/driver_module_view_model.dart';
export 'modules/user/view_models/user_module_view_model.dart';
export 'presentation/screens/driver_module_hub_screen.dart';
export 'presentation/screens/operations_module_hub_screen.dart';
export 'presentation/screens/user_module_hub_screen.dart';
export 'routing/admin_route_catalog.dart';
